name: pandapower_final
channels:
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - nbformat
  - pip
  - pip:
    - pandapower
    - plotly
    - matplotlib
    - numba
    - networkx
    - numpy
    - seaborn
    - openpyxl
