name: pandapower
channels:
  - defaults
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - pandapower
    - plotly
    - matplotlib
    - numba
    - networkx
    - numpy
    - seaborn
    - ipykernel